### PR TITLE
Add base64_decodebytes and base64_encodebytes

### PR DESCRIPTION
**Pull request by webknjaz**
`*string` names of functions are deprecated while still are aliased to their `*bytes` versions.

### CODE REVIEW

**Comment by MeTaNoV** [comment]
Would be useful to solve this issue: https://github.com/altair-viz/altair/issues/994

**Comment by jaraco** [comment]
According to [the docs](https://docs.python.org/2/library/base64.html) decodestring is a legacy interface. Why not just use `base64.b64decode/encode`?

**Comment by webknjaz** [comment]
Makes sense

**Comment by benjaminp** [comment]
Thanks for the PR, but I agree that it's best to just migrate to the modern interfaces.

**Pull request closed without merging**
