### PR TITLE
Add unquote_to_bytes to moved urllib.parse. Fixes #171.

### LINKED ISSUE #171: unquote_to_bytes missing from urllib.parse
CherryPy uses `urllib.parse.unquote_to_bytes` on Python 3 and `urllib.unquote` on Python 2 (with no other special handling.  Perhaps six could provide that same compatibility.

### PR DESCRIPTION
**Pull request by jaraco**

### CODE REVIEW

**Comment by benjaminp** [comment]
Thanks for the PR. Could you
1. update the table in `documentation/index.rst`,
2. add a (probably sundry) test to `test_six.py`?

**Comment by jaraco** [comment]
Yes

**Comment by jaraco** [comment]
I've added docs... and [there's already a test that covers the attribute](https://github.com/benjaminp/six/blob/1.10.0/test_six.py#L121-L131).

**Comment by jaraco** [comment]
If it weren't for #182, you could demonstrate that the test was being run by invoking `tox -- -k unquote_to_bytes`.

**Comment by jaraco** [comment]
Merging the changes from [the issue-182 branch](/jaraco/six/tree/issue-182), it can be show that the tests are run:

```
$ git checkout unquote_to_bytes 
Switched to branch 'unquote_to_bytes'
Your branch is up-to-date with 'origin/unquote_to_bytes'.
$ git merge issue-182
Merge made by the 'recursive' strategy.
 tox.ini | 5 ++++-
 1 file changed, 4 insertions(+), 1 deletion(-)
$ tox -e py -- -k unquote_to_bytes -v
py recreate: /Users/jaraco/Dropbox/code/public/six/.tox/py
py installdeps: pytest, git+https://github.com/jaraco/pip@hotfix/issue4264-2
py develop-inst: /Users/jaraco/Dropbox/code/public/six
py installed: appdirs==1.4.2,packaging==16.8,py==1.4.32,pyparsing==2.1.10,pytest==3.0.6,-e git+gh://jaraco/six@0bb369282df2fb1364f44fabc501d8817ea79cec#egg=six
py runtests: PYTHONHASHSEED='4129616605'
py runtests: commands[0] | py.test -rfsxX -k unquote_to_bytes -v
====================================== test session starts =======================================
platform darwin -- Python 3.6.0, pytest-3.0.6, py-1.4.32, pluggy-0.4.0 -- /Users/jaraco/Dropbox/code/public/six/.tox/py/bin/python3
cachedir: .cache
rootdir: /Users/jaraco/Dropbox/code/public/six, inifile: setup.cfg
collected 189 items 

test_six.py::test_move_items_urllib_parse[unquote_to_bytes] PASSED

===================================== pytest-warning summary =====================================
WC1 None [pytest] section in setup.cfg files is deprecated, use [tool:pytest] instead.
====================================== 188 tests deselected ======================================
================== 1 passed, 188 deselected, 1 pytest-warnings in 0.08 seconds ===================
____________________________________________ summary _____________________________________________
  py: commands succeeded
  congratulations :)
```

**Pull request merged**
