### PR TITLE
Ndbm move

### PR DESCRIPTION
**Pull request by firba1**
refs #298

### CODE REVIEW

**Comment by graingert** [comment]
are we missing https://github.com/python/cpython/blob/master/Lib/lib2to3/fixes/fix_imports.py#L8-L58

**Comment by graingert** [comment]
also some other dbm things https://github.com/python/cpython/blob/master/Lib/lib2to3/fixes/fix_imports2.py#L7-L8

**Comment by firba1** [comment]
There's a "not finished" PR for one of those. https://github.com/benjaminp/six/pull/180

**Comment by firba1** [comment]
If you want me to add more moves, I'm happy to do so, but this is the one I really care about.

**Comment by graingert** [comment]
I'd like to see a comprehensive PR will all the moves added, but I'm not the maintainer and I believe this package is now unmaintained

@benjaminp ^

**Comment by benjaminp** [comment]
The `six.moves` name should be `dbm_ndbm`.

**Comment by firba1** [comment]
Should I add the other dbm moves as part of this branch?

**Comment by benjaminp** [comment]
Which are those?

**Comment by firba1** [comment]
anydbm and whichdb

**Comment by firba1** [comment]
ah and dumbdbm

**Pull request merged**
