### PR TITLE
Update classifiers

### PR DESCRIPTION
**Pull request by hugovk**

### CODE REVIEW

**Comment by benjaminp** [comment]
I'm not sure I see the point of enumerating every possible Python version.

**Comment by hugovk** [comment]
Not every possible, just those that are officially supported by six. It makes it explicit for both programs and people accessing PYPI.

**Comment by jdufresne** [comment]
> I'm not sure I see the point of enumerating every possible Python version.

It is common practice to enumerate all supported versions in most of the maintained packages I see and use.

**Comment by hugovk** [comment]
`python_requires` was added in https://github.com/benjaminp/six/pull/224.

**Pull request closed without merging**
