### PR TITLE
Add pytest as tests_require

### PR DESCRIPTION
**Pull request by toabctl**
When running the six testsuite, pytest is needed.

### CODE REVIEW

**Comment by toabctl** [comment]
@benjaminp This is needed because six needs pytest when running the tests.

**Comment by benjaminp** [comment]
Thanks for the PR. What is this good for? We don't really use `setup.py test` instead preferring tox.

**Comment by toabctl** [comment]
> Thanks for the PR. What is this good for? We don't really use setup.py test instead preferring tox.

@benjaminp Downstream (eg linux distros) who package six can then during the build process call the unittests via ```python setup.py test```. That's why it is good to have the correct ```test_requires``` and ```setup_requires```. And also the correct ```setup.py test``` integration

**Comment by toabctl** [comment]
And also we (openSUSE distro) try to automatically convert sdist tarballs to rpm packages. And correct rquirements are needed for that.

**Pull request merged**
